# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ms2.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1927, 2751)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(211, 11, 50, 16))
        self.pushButton_6.setStyleSheet("border:none;")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/pptScreenshot.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon)
        self.pushButton_6.setObjectName("pushButton_6")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(750, 10, 271, 71))
        self.label_16.setStyleSheet("image: url(:/img/dss.png);")
        self.label_16.setText("")
        self.label_16.setObjectName("label_16")
        self.line_9 = QtWidgets.QFrame(self.centralwidget)
        self.line_9.setGeometry(QtCore.QRect(170, 640, 20, 16))
        self.line_9.setStyleSheet("background-color:lightgrey")
        self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_10.setGeometry(QtCore.QRect(1090, 640, 24, 16))
        self.pushButton_10.setStyleSheet("border:none;background-color:lightgrey")
        self.pushButton_10.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/img/Screeshot.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_10.setIcon(icon1)
        self.pushButton_10.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_10.setObjectName("pushButton_10")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(90, 640, 72, 16))
        self.label_8.setStyleSheet("background-color:lightgrey")
        self.label_8.setObjectName("label_8")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(50, 20, 51, 21))
        self.pushButton_3.setStyleSheet("background-color:white;border:none;")
        self.pushButton_3.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/img/download (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon2)
        self.pushButton_3.setCheckable(True)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_13 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_13.setGeometry(QtCore.QRect(1320, 640, 20, 16))
        self.pushButton_13.setStyleSheet("background-color:lightgrey;border:none;")
        self.pushButton_13.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/img/mm.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_13.setIcon(icon3)
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_11 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_11.setGeometry(QtCore.QRect(1110, 640, 20, 16))
        self.pushButton_11.setStyleSheet("background-color:lightgrey;border:none;")
        self.pushButton_11.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/img/l.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_11.setIcon(icon4)
        self.pushButton_11.setObjectName("pushButton_11")
        self.textEdit_4 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_4.setGeometry(QtCore.QRect(220, 590, 1131, 41))
        self.textEdit_4.setPlaceholderText("")
        self.textEdit_4.setObjectName("textEdit_4")
        self.line_8 = QtWidgets.QFrame(self.centralwidget)
        self.line_8.setGeometry(QtCore.QRect(1180, 0, 20, 91))
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.pushButton_16 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_16.setGeometry(QtCore.QRect(0, 100, 81, 23))
        self.pushButton_16.setStyleSheet("background-color:lightgrey;border:none")
        self.pushButton_16.setObjectName("pushButton_16")
        self.textEdit_3 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_3.setGeometry(QtCore.QRect(0, 630, 1351, 31))
        self.textEdit_3.setStyleSheet("background-color:lightgrey")
        self.textEdit_3.setObjectName("textEdit_3")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(430, 10, 41, 31))
        self.label_11.setStyleSheet("image: url(:/img/s.png);")
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(50, 40, 51, 31))
        self.pushButton_4.setStyleSheet("border:none")
        self.pushButton_4.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/img/download.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon5)
        self.pushButton_4.setCheckable(True)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(160, 0, 41, 41))
        self.pushButton_5.setStyleSheet("border:none;")
        self.pushButton_5.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/img/7630743_f260.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon6)
        self.pushButton_5.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_5.setObjectName("pushButton_5")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(100, 0, 20, 91))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(850, 80, 47, 13))
        self.label_5.setObjectName("label_5")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(600, 80, 61, 16))
        self.label_4.setObjectName("label_4")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(480, 50, 31, 31))
        self.label_14.setStyleSheet("image: url(:/img/cc.png);")
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(270, 0, 16, 91))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.pushButton_18 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_18.setGeometry(QtCore.QRect(190, 103, 21, 20))
        self.pushButton_18.setStyleSheet("background-color:silver;border:none")
        self.pushButton_18.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/img/close_1-512.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_18.setIcon(icon7)
        self.pushButton_18.setIconSize(QtCore.QSize(12, 16))
        self.pushButton_18.setObjectName("pushButton_18")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 80, 47, 13))
        self.label.setObjectName("label")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(10, 130, 191, 131))
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap(":/img/sli.png"))
        self.label_10.setScaledContents(True)
        self.label_10.setWordWrap(False)
        self.label_10.setObjectName("label_10")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(1170, 640, 23, 16))
        self.label_9.setStyleSheet("background-color:lightgrey")
        self.label_9.setObjectName("label_9")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(270, 40, 221, 41))
        self.label_13.setStyleSheet("image: url(:/img/,.png);")
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(50, 0, 51, 21))
        self.pushButton_2.setAutoFillBackground(False)
        self.pushButton_2.setStyleSheet("background-color:white;border:none;")
        self.pushButton_2.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/img/download.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon8)
        self.pushButton_2.setCheckable(True)
        self.pushButton_2.setChecked(False)
        self.pushButton_2.setObjectName("pushButton_2")
        self.comboBox_3 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_3.setGeometry(QtCore.QRect(280, 10, 101, 22))
        self.comboBox_3.setObjectName("comboBox_3")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setEnabled(False)
        self.textEdit.setGeometry(QtCore.QRect(220, 100, 1131, 481))
        self.textEdit.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.textEdit.setAcceptDrops(True)
        self.textEdit.setAutoFillBackground(False)
        self.textEdit.setStyleSheet("background-color:silver")
        self.textEdit.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textEdit.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textEdit.setLineWidth(0)
        self.textEdit.setUndoRedoEnabled(True)
        self.textEdit.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.textEdit.setObjectName("textEdit")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(480, 10, 31, 31))
        self.label_12.setStyleSheet("image: url(:/img/d.png);")
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(380, 80, 47, 13))
        self.label_3.setObjectName("label_3")
        self.pushButton_17 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_17.setGeometry(QtCore.QRect(80, 100, 71, 23))
        self.pushButton_17.setStyleSheet("background-color:darkgrey")
        self.pushButton_17.setObjectName("pushButton_17")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setEnabled(True)
        self.label_7.setGeometry(QtCore.QRect(30, 640, 53, 16))
        self.label_7.setAutoFillBackground(False)
        self.label_7.setStyleSheet("background-color:lightgrey")
        self.label_7.setScaledContents(False)
        self.label_7.setWordWrap(False)
        self.label_7.setObjectName("label_7")
        self.pushButton_14 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_14.setGeometry(QtCore.QRect(1190, 640, 21, 20))
        self.pushButton_14.setStyleSheet("background-color:lightgrey;border:none;")
        self.pushButton_14.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/img/pl.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_14.setIcon(icon9)
        self.pushButton_14.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_14.setObjectName("pushButton_14")
        self.textEdit_5 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_5.setGeometry(QtCore.QRect(0, 100, 211, 531))
        self.textEdit_5.setStyleSheet("background-color:silver")
        self.textEdit_5.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEdit_5.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.textEdit_5.setOverwriteMode(False)
        self.textEdit_5.setObjectName("textEdit_5")
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(170, 50, 20, 16))
        self.comboBox_2.setStyleSheet("border:none")
        self.comboBox_2.setObjectName("comboBox_2")
        self.line_12 = QtWidgets.QFrame(self.centralwidget)
        self.line_12.setGeometry(QtCore.QRect(150, 110, 61, 31))
        self.line_12.setStyleSheet("background-color:silver")
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(730, 0, 20, 91))
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(630, 290, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.line_7 = QtWidgets.QFrame(self.centralwidget)
        self.line_7.setGeometry(QtCore.QRect(1030, 0, 20, 91))
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(210, 100, 16, 531))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.comboBox_4 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_4.setGeometry(QtCore.QRect(380, 10, 41, 22))
        self.comboBox_4.setObjectName("comboBox_4")
        self.line_14 = QtWidgets.QFrame(self.centralwidget)
        self.line_14.setGeometry(QtCore.QRect(470, 50, 20, 21))
        self.line_14.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(20, 50, 20, 16))
        self.comboBox.setStyleSheet("border:none;")
        self.comboBox.setCurrentText("")
        self.comboBox.setObjectName("comboBox")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(520, 10, 221, 71))
        self.label_15.setStyleSheet("image: url(:/img/sss.png);")
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(1070, 10, 101, 71))
        self.label_17.setStyleSheet("image: url(:/img/sxsx.png);")
        self.label_17.setText("")
        self.label_17.setObjectName("label_17")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(211, 55, 54, 16))
        self.pushButton_8.setStyleSheet("border:none;")
        self.pushButton_8.setIcon(icon1)
        self.pushButton_8.setObjectName("pushButton_8")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(1110, 80, 31, 16))
        self.label_6.setObjectName("label_6")
        self.line_13 = QtWidgets.QFrame(self.centralwidget)
        self.line_13.setGeometry(QtCore.QRect(470, 10, 20, 21))
        self.line_13.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(510, 0, 20, 91))
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.pushButton_15 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_15.setGeometry(QtCore.QRect(1290, 640, 20, 16))
        self.pushButton_15.setStyleSheet("background-color:lightgrey;border:none;")
        self.pushButton_15.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/img/mk.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_15.setIcon(icon10)
        self.pushButton_15.setObjectName("pushButton_15")
        self.line_10 = QtWidgets.QFrame(self.centralwidget)
        self.line_10.setGeometry(QtCore.QRect(80, 640, 16, 16))
        self.line_10.setStyleSheet("background-color:lightgrey")
        self.line_10.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setEnabled(False)
        self.label_20.setGeometry(QtCore.QRect(650, 370, 191, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(0, 90, 1351, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(211, 33, 45, 16))
        self.pushButton_7.setStyleSheet("border:none;")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/img/pptScreeshot.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_7.setIcon(icon11)
        self.pushButton_7.setObjectName("pushButton_7")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(200, 80, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setEnabled(True)
        self.label_18.setGeometry(QtCore.QRect(480, 130, 521, 421))
        self.label_18.setStyleSheet("image: url(:/img/dddd.png);\n"
"background-color:silver;\n"
"")
        self.label_18.setText("")
        self.label_18.setObjectName("label_18")
        self.line_11 = QtWidgets.QFrame(self.centralwidget)
        self.line_11.setGeometry(QtCore.QRect(1050, 640, 20, 16))
        self.line_11.setStyleSheet("background-color:lightgrey")
        self.line_11.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(0, 0, 51, 51))
        self.pushButton.setStyleSheet("#paste {\n"
"background-color:transparent;\n"
"\n"
"    border-image: url(:/img/images.jpg);\n"
"background:none;\n"
"border:10px\n"
";\n"
"}\n"
"")
        self.pushButton.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/img/images.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon12)
        self.pushButton.setIconSize(QtCore.QSize(400, 50))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_12 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_12.setGeometry(QtCore.QRect(1140, 640, 20, 16))
        self.pushButton_12.setStyleSheet("background-color:lightgrey;border:none;")
        self.pushButton_12.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/img/ll.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_12.setIcon(icon13)
        self.pushButton_12.setObjectName("pushButton_12")
        self.horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider.setGeometry(QtCore.QRect(1210, 640, 84, 16))
        self.horizontalSlider.setStyleSheet("background-color:lightgrey")
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(1070, 640, 24, 16))
        self.pushButton_9.setMouseTracking(False)
        self.pushButton_9.setStyleSheet("border:none;background-color:lightgrey;")
        self.pushButton_9.setText("")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/img/p.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_9.setIcon(icon14)
        self.pushButton_9.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_9.setCheckable(False)
        self.pushButton_9.setChecked(False)
        self.pushButton_9.setObjectName("pushButton_9")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(100, 640, 72, 16))
        self.label_21.setStyleSheet("background-color:lightgrey")
        self.label_21.setObjectName("label_21")
        self.pushButton_19 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_19.setGeometry(QtCore.QRect(1100, 640, 24, 16))
        self.pushButton_19.setStyleSheet("border:none;background-color:lightgrey")
        self.pushButton_19.setText("")
        self.pushButton_19.setIcon(icon1)
        self.pushButton_19.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_19.setObjectName("pushButton_19")
        self.pushButton_20 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_20.setGeometry(QtCore.QRect(1120, 640, 20, 16))
        self.pushButton_20.setStyleSheet("background-color:lightgrey;border:none;")
        self.pushButton_20.setText("")
        self.pushButton_20.setIcon(icon4)
        self.pushButton_20.setObjectName("pushButton_20")
        self.pushButton_21 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_21.setGeometry(QtCore.QRect(0, 100, 81, 23))
        self.pushButton_21.setStyleSheet("background-color:lightgrey;border:none")
        self.pushButton_21.setObjectName("pushButton_21")
        self.pushButton_22 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_22.setGeometry(QtCore.QRect(80, 100, 71, 23))
        self.pushButton_22.setStyleSheet("background-color:darkgrey")
        self.pushButton_22.setObjectName("pushButton_22")
        self.pushButton_23 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_23.setGeometry(QtCore.QRect(200, 100, 21, 20))
        self.pushButton_23.setStyleSheet("background-color:silver;border:none")
        self.pushButton_23.setText("")
        self.pushButton_23.setIcon(icon7)
        self.pushButton_23.setIconSize(QtCore.QSize(12, 16))
        self.pushButton_23.setObjectName("pushButton_23")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(480, 150, 521, 371))
        self.label_22.setStyleSheet("image: url(:/img/Screenshot (2).png);")
        self.label_22.setText("")
        self.label_22.setObjectName("label_22")
        self.verticalScrollBar_2 = QtWidgets.QScrollBar(self.centralwidget)
        self.verticalScrollBar_2.setGeometry(QtCore.QRect(1330, 100, 20, 481))
        self.verticalScrollBar_2.setMinimum(1)
        self.verticalScrollBar_2.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar_2.setObjectName("verticalScrollBar_2")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(10, 120, 211, 511))
        self.scrollArea.setStyleSheet("background-color:silver")
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 192, 1000))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(100, 1000))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.pushButton_24 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_24.setGeometry(QtCore.QRect(0, -1, 191, 141))
        self.pushButton_24.setText("")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/img/x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_24.setIcon(icon15)
        self.pushButton_24.setIconSize(QtCore.QSize(500, 500))
        self.pushButton_24.setObjectName("pushButton_24")
        self.pushButton_25 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_25.setGeometry(QtCore.QRect(0, 140, 191, 151))
        self.pushButton_25.setText("")
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/img/xx.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_25.setIcon(icon16)
        self.pushButton_25.setIconSize(QtCore.QSize(500, 500))
        self.pushButton_25.setObjectName("pushButton_25")
        self.pushButton_26 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_26.setGeometry(QtCore.QRect(0, 290, 191, 151))
        self.pushButton_26.setText("")
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/img/xxcs.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_26.setIcon(icon17)
        self.pushButton_26.setIconSize(QtCore.QSize(500, 500))
        self.pushButton_26.setObjectName("pushButton_26")
        self.pushButton_27 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_27.setGeometry(QtCore.QRect(0, 440, 191, 141))
        self.pushButton_27.setText("")
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/img/re.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_27.setIcon(icon18)
        self.pushButton_27.setIconSize(QtCore.QSize(500, 500))
        self.pushButton_27.setObjectName("pushButton_27")
        self.pushButton_28 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_28.setGeometry(QtCore.QRect(0, 580, 191, 141))
        self.pushButton_28.setText("")
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(":/img/Capture.PNG"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_28.setIcon(icon19)
        self.pushButton_28.setIconSize(QtCore.QSize(500, 500))
        self.pushButton_28.setObjectName("pushButton_28")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.textEdit.raise_()
        self.pushButton_6.raise_()
        self.label_16.raise_()
        self.line_9.raise_()
        self.pushButton_10.raise_()
        self.label_8.raise_()
        self.pushButton_3.raise_()
        self.pushButton_13.raise_()
        self.pushButton_11.raise_()
        self.textEdit_4.raise_()
        self.line_8.raise_()
        self.pushButton_16.raise_()
        self.textEdit_3.raise_()
        self.label_11.raise_()
        self.pushButton_4.raise_()
        self.pushButton_5.raise_()
        self.line.raise_()
        self.label_5.raise_()
        self.label_4.raise_()
        self.label_14.raise_()
        self.line_3.raise_()
        self.pushButton_18.raise_()
        self.label.raise_()
        self.label_10.raise_()
        self.label_9.raise_()
        self.label_13.raise_()
        self.pushButton_2.raise_()
        self.comboBox_3.raise_()
        self.label_12.raise_()
        self.label_3.raise_()
        self.pushButton_17.raise_()
        self.label_7.raise_()
        self.pushButton_14.raise_()
        self.textEdit_5.raise_()
        self.comboBox_2.raise_()
        self.line_12.raise_()
        self.line_6.raise_()
        self.label_19.raise_()
        self.line_7.raise_()
        self.line_4.raise_()
        self.comboBox_4.raise_()
        self.line_14.raise_()
        self.comboBox.raise_()
        self.label_15.raise_()
        self.label_17.raise_()
        self.pushButton_8.raise_()
        self.label_6.raise_()
        self.line_13.raise_()
        self.line_5.raise_()
        self.pushButton_15.raise_()
        self.line_10.raise_()
        self.label_20.raise_()
        self.line_2.raise_()
        self.pushButton_7.raise_()
        self.label_2.raise_()
        self.label_18.raise_()
        self.line_11.raise_()
        self.pushButton.raise_()
        self.pushButton_12.raise_()
        self.horizontalSlider.raise_()
        self.pushButton_9.raise_()
        self.label_21.raise_()
        self.pushButton_19.raise_()
        self.pushButton_20.raise_()
        self.pushButton_21.raise_()
        self.pushButton_22.raise_()
        self.pushButton_23.raise_()
        self.label_22.raise_()
        self.verticalScrollBar_2.raise_()
        self.scrollArea.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1927, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_Home = QtWidgets.QMenu(self.menubar)
        self.menu_Home.setObjectName("menu_Home")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        self.menuInsert = QtWidgets.QMenu(self.menubar)
        self.menuInsert.setObjectName("menuInsert")
        self.menu_4 = QtWidgets.QMenu(self.menubar)
        self.menu_4.setObjectName("menu_4")
        self.menu_5 = QtWidgets.QMenu(self.menubar)
        self.menu_5.setObjectName("menu_5")
        self.menuDesign = QtWidgets.QMenu(self.menubar)
        self.menuDesign.setObjectName("menuDesign")
        self.menu_6 = QtWidgets.QMenu(self.menubar)
        self.menu_6.setObjectName("menu_6")
        self.menu_7 = QtWidgets.QMenu(self.menubar)
        self.menu_7.setObjectName("menu_7")
        self.menuTransitions = QtWidgets.QMenu(self.menubar)
        self.menuTransitions.setObjectName("menuTransitions")
        self.menu_8 = QtWidgets.QMenu(self.menubar)
        self.menu_8.setObjectName("menu_8")
        self.menu_9 = QtWidgets.QMenu(self.menubar)
        self.menu_9.setObjectName("menu_9")
        self.menuAnimations = QtWidgets.QMenu(self.menubar)
        self.menuAnimations.setObjectName("menuAnimations")
        self.menu_10 = QtWidgets.QMenu(self.menubar)
        self.menu_10.setObjectName("menu_10")
        self.menu_11 = QtWidgets.QMenu(self.menubar)
        self.menu_11.setObjectName("menu_11")
        self.menuSlide_Show = QtWidgets.QMenu(self.menubar)
        self.menuSlide_Show.setObjectName("menuSlide_Show")
        self.menu_12 = QtWidgets.QMenu(self.menubar)
        self.menu_12.setObjectName("menu_12")
        self.menu_13 = QtWidgets.QMenu(self.menubar)
        self.menu_13.setObjectName("menu_13")
        self.menuReview = QtWidgets.QMenu(self.menubar)
        self.menuReview.setObjectName("menuReview")
        self.menu_14 = QtWidgets.QMenu(self.menubar)
        self.menu_14.setObjectName("menu_14")
        self.menu_15 = QtWidgets.QMenu(self.menubar)
        self.menu_15.setObjectName("menu_15")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionHome = QtWidgets.QAction(MainWindow)
        self.actionHome.setObjectName("actionHome")
        self.menu_2.addAction(self.actionHome)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_Home.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menuInsert.menuAction())
        self.menubar.addAction(self.menu_4.menuAction())
        self.menubar.addAction(self.menu_5.menuAction())
        self.menubar.addAction(self.menuDesign.menuAction())
        self.menubar.addAction(self.menu_6.menuAction())
        self.menubar.addAction(self.menu_7.menuAction())
        self.menubar.addAction(self.menuTransitions.menuAction())
        self.menubar.addAction(self.menu_8.menuAction())
        self.menubar.addAction(self.menu_9.menuAction())
        self.menubar.addAction(self.menuAnimations.menuAction())
        self.menubar.addAction(self.menu_10.menuAction())
        self.menubar.addAction(self.menu_11.menuAction())
        self.menubar.addAction(self.menuSlide_Show.menuAction())
        self.menubar.addAction(self.menu_12.menuAction())
        self.menubar.addAction(self.menu_13.menuAction())
        self.menubar.addAction(self.menuReview.menuAction())
        self.menubar.addAction(self.menu_14.menuAction())
        self.menubar.addAction(self.menu_15.menuAction())
        self.menubar.addAction(self.menuView.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_6.setText(_translate("MainWindow", "layout"))
        self.label_8.setText(_translate("MainWindow", "\"Office Theme\""))
        self.textEdit_4.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Click to add notes</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.pushButton_16.setText(_translate("MainWindow", "Slides"))
        self.label_5.setText(_translate("MainWindow", "Drawing"))
        self.label_4.setText(_translate("MainWindow", "Paragraph"))
        self.label.setText(_translate("MainWindow", "Clipboard"))
        self.label_9.setText(_translate("MainWindow", "39%"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "Font"))
        self.pushButton_17.setText(_translate("MainWindow", "Outline"))
        self.label_7.setText(_translate("MainWindow", "Slide 1 of 1"))
        self.label_19.setText(_translate("MainWindow", "Click to add title"))
        self.pushButton_8.setText(_translate("MainWindow", "section"))
        self.label_6.setText(_translate("MainWindow", "Editing"))
        self.label_20.setText(_translate("MainWindow", "Click to add subtitle"))
        self.pushButton_7.setText(_translate("MainWindow", "reset"))
        self.label_2.setText(_translate("MainWindow", "Slides"))
        self.label_21.setText(_translate("MainWindow", "\"Office Theme\""))
        self.pushButton_21.setText(_translate("MainWindow", "Slides"))
        self.pushButton_22.setText(_translate("MainWindow", "Outline"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menu.setTitle(_translate("MainWindow", " "))
        self.menu_2.setTitle(_translate("MainWindow", " Home"))
        self.menu_Home.setTitle(_translate("MainWindow", " "))
        self.menu_3.setTitle(_translate("MainWindow", " "))
        self.menuInsert.setTitle(_translate("MainWindow", "Insert"))
        self.menu_4.setTitle(_translate("MainWindow", " "))
        self.menu_5.setTitle(_translate("MainWindow", " "))
        self.menuDesign.setTitle(_translate("MainWindow", "Design"))
        self.menu_6.setTitle(_translate("MainWindow", " "))
        self.menu_7.setTitle(_translate("MainWindow", " "))
        self.menuTransitions.setTitle(_translate("MainWindow", "Transitions"))
        self.menu_8.setTitle(_translate("MainWindow", " "))
        self.menu_9.setTitle(_translate("MainWindow", " "))
        self.menuAnimations.setTitle(_translate("MainWindow", "Animations"))
        self.menu_10.setTitle(_translate("MainWindow", " "))
        self.menu_11.setTitle(_translate("MainWindow", " "))
        self.menuSlide_Show.setTitle(_translate("MainWindow", "Slide Show"))
        self.menu_12.setTitle(_translate("MainWindow", " "))
        self.menu_13.setTitle(_translate("MainWindow", " "))
        self.menuReview.setTitle(_translate("MainWindow", "Review"))
        self.menu_14.setTitle(_translate("MainWindow", " "))
        self.menu_15.setTitle(_translate("MainWindow", " "))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.actionHome.setText(_translate("MainWindow", "Home"))
import img_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
